### ISSUE TITLE
OAuth sign-in "hidden" in sign-up area.

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/Moodle_Saylor#2]
Users might not immediately be able to find the OAuth sign-in buttons when trying to log in if they fail to look in the sign-up area (the latter is more hidden on mobile).

![oauth ux](https://user-images.githubusercontent.com/10980346/32727649-3c9c9558-c84b-11e7-84a2-0a705385e9b4.png)

**Comment by jazinheira** [comment]
Fixed
