### ISSUE TITLE
Privacy and Terms repetitive title/description/title

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/Moodle_Saylor#5]
E.g. the phrase "Terms of Use" appears several times in the first few lines (1. Moodle's title; 2. Moodle's description field; 3. page content title)[Image 1]. The redundancy is replicated in the signup process [Image 2].

Since the Moodle title is a given and the description field is required, some options include:

1. Revise description to be more explanatory, e.g. "This page include conditions governing your use of Saylor Academy" or similar.
2. Remove the title from the actual content -- e.g. start the content immediately with the table of contents.

<hr>

![image](https://user-images.githubusercontent.com/10980346/55961953-f71acd00-5c3d-11e9-92c2-dd01bc3496e4.png)

<hr>

![image](https://user-images.githubusercontent.com/10980346/55962295-950e9780-5c3e-11e9-8f5a-5362efbe7de4.png)

**Comment by jazinheira** [comment]
True - we can edit the doc. I think it had that title in the doc body and it doesn't need to be there.
@neonacorns Any thoughts on a better description/summary?
