### ISSUE TITLE
Create canonical Terms and Privacy pages

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/Moodle_Saylor#6]
Policies displayed to users at signup are duplicates of WordPress content (the versions linked from site footers).

That allows for the human-error possibility that changes to one version would not be made in the other.

Ideally, recommend canonical terms/privacy locations that everything would point to.

**Comment by jazinheira** [comment]
Not possible - policy versions are saved in Moodle for compliance reasons.

@neonacorns If content in the TOU or Privacy Policy is being updated PLEASE let me know! Users need to accept the new versions.

We could include versioning within the TOU or PP themselves. I'd recommend something similar to Moodle's versioning YYYYMMDDRR ie 2019041100.
